name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
    contents: write
    pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f
        with:
          commit-message: Update CHANGELOG
          branch: create-pull-request/changelog-updater-action
          delete-branch: true
          title: 'Update Changelog'
          body: |
            Update Changelog
            - Updated with latest changelog
